name: dicoding_submission
description: "Flutter Project For Dicoding Submission. Handcrafted and Made with ❤️ by Raihan Fadli"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  auto_size_text: 3.0.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  intl: ^0.19.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  toggle_switch: ^2.3.0
  stacked_card_carousel: ^0.0.4
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  assets: 
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family : Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather-Italic.ttf
          style: italic
  uses-material-design: true